# Generated by Django 3.2.6 on 2022-03-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_userlevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='usernameChangeCount',
            field=models.IntegerField(default=0),
        ),
    ]
