# Generated by Django 3.2.6 on 2021-08-17 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='last_post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
