# Generated by Django 3.2.6 on 2021-08-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_thread_last_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subforum',
            name='titleURL',
        ),
        migrations.AlterField(
            model_name='subforum',
            name='title',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
