# Generated by Django 3.2.6 on 2021-08-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20210817_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='subforum',
            name='titleURL',
            field=models.CharField(default='test', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subforum',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
