# Generated by Django 3.2.6 on 2021-08-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20210817_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subforum',
            name='titleURL',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
