# Generated by Django 3.2.6 on 2021-08-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_thread_viewcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='isLocked',
            field=models.BooleanField(default=False),
        ),
    ]
