# Generated by Django 3.2.6 on 2021-09-11 17:53

from django.db import migrations, models
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_subforum_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subforum',
            name='image',
            field=models.ImageField(default='subforum_icon/default.png', upload_to=forum.models.subforumIconImagePath),
        ),
    ]
