# Generated by Django 3.2.6 on 2021-09-11 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_alter_subforum_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subforum',
            name='image',
        ),
    ]
